/*
 * Copyright 2026 Ronny Trommer <ronny@no42.org>
 * SPDX-License-Identifier: Apache-2.0
 */

//! Schema-emission infrastructure for the `kind: User` YAML document.
//!
//! The actual JSON Schema is generated by `examples/gen_schema.rs` from
//! the `schemars` derives on the `model` types, with project-specific
//! `x-onmsctl-list-kind` annotations injected by walking the produced
//! schema and amending list-field entries — the same convention as
//! `onmsctl_provisioning::schema`.
//!
//! This module owns the single authoritative annotation table so the
//! generator and the drift-check test cannot diverge by hand-copy.

/// One entry in the project's annotation table: (definition name in
/// `$defs`, property name on that definition, `ListKind` string literal
/// the diff engine will read). The kind literal is what lands as the
/// `x-onmsctl-list-kind` value in the schema; the generator also
/// derives `uniqueItems: true` on `set`-kind entries so editors catch
/// duplicates at edit-time.
pub type ListAnnotation = (&'static str, &'static str, &'static str);

/// Single source of truth for the list-kind annotation table. Consumed by
/// both `examples/gen_schema.rs` (post-processes the schema) and
/// `tests/schema_drift.rs` (verifies committed-schema fidelity).
///
/// IAM has exactly one set-shaped field today — `spec.roles`. Duplicate
/// roles are already rejected at parse time by `deserialize_unique_roles`;
/// the `set` kind here mirrors that contract into the editor-facing schema
/// (`uniqueItems: true`).
pub const ANNOTATIONS: &[ListAnnotation] = &[("UserSpec", "roles", "set")];
